name: Bank Activity Notifier

on:
  schedule:
    # 每天早上 3:00 (UTC 0)-->台灣時間下午 11:00 
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install selenium pandas requests

    - name: Run script
      env:
        LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
        LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
      run: python main.py